version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=localhost
      - DB_PORT=5432
      - DATABASE_NAME=leaderboard
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
  database:
    image: postgres
    environment:
      POSTGRES_DB: leaderboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
